stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.pkg.github.com/fr34kyn01535/eco-server/eco-server:latest
      pushRemote: true
      registry: docker.pkg.github.com
timeout: 60
notification: {}
