stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: fr34kyn01535/eco-server
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
